;;; flash-emacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from demo-clean-interface.el

(register-definition-prefixes "demo-clean-interface" '("demo-"))


;;; Generated autoloads from flash-emacs.el

(autoload 'flash-emacs-jump "flash-emacs" "\
Start flash jump mode.
Type characters to search, then use the displayed labels to jump." t)
(register-definition-prefixes "flash-emacs" '("flash-emacs-"))


;;; Generated autoloads from install.el

(register-definition-prefixes "install" '("flash-emacs-install"))

;;; End of scraped data

(provide 'flash-emacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flash-emacs-autoloads.el ends here
